// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthPayload struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type CreateOrderInput struct {
	Items []*OrderItemInput `json:"items"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type OrderItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
}

type OrderPage struct {
	Items       []*Order `json:"items"`
	Total       int      `json:"total"`
	Page        int      `json:"page"`
	PageSize    int      `json:"pageSize"`
	HasNextPage bool     `json:"hasNextPage"`
}

type Product struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Price     float64   `json:"price"`
	Stock     int       `json:"stock"`
	CreatedAt time.Time `json:"createdAt"`
}

type ProductFilter struct {
	Name     *string  `json:"name,omitempty"`
	MinPrice *float64 `json:"minPrice,omitempty"`
	MaxPrice *float64 `json:"maxPrice,omitempty"`
}

type ProductPage struct {
	Items       []*Product `json:"items"`
	Total       int        `json:"total"`
	Page        int        `json:"page"`
	PageSize    int        `json:"pageSize"`
	HasNextPage bool       `json:"hasNextPage"`
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
}
