package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/nicolas2601/go-graphql-orders-api/internal/delivery/graphql/authctx"
	"github.com/nicolas2601/go-graphql-orders-api/internal/delivery/graphql/generated"
	"github.com/nicolas2601/go-graphql-orders-api/internal/delivery/graphql/model"
	"github.com/nicolas2601/go-graphql-orders-api/internal/domain"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	pair, user, err := r.auth.Register(ctx, input.Email, input.Password)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toAuthPayload(pair, user), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	pair, user, err := r.auth.Login(ctx, input.Email, input.Password)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toAuthPayload(pair, user), nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.AuthPayload, error) {
	pair, user, err := r.auth.Refresh(ctx, token)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toAuthPayload(pair, user), nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	order, err := r.orders.Create(ctx, userID, toOrderLines(input.Items))
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toOrderModel(order), nil
}

// ConfirmOrder is the resolver for the confirmOrder field.
func (r *mutationResolver) ConfirmOrder(ctx context.Context, id string) (*model.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	order, err := r.orders.Confirm(ctx, userID, id)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toOrderModel(order), nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, id string) (*model.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	order, err := r.orders.Cancel(ctx, userID, id)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toOrderModel(order), nil
}

// User is the resolver for the user field. Resuelve el dueno de la orden por su id.
func (r *orderResolver) User(ctx context.Context, obj *model.Order) (*model.User, error) {
	user, err := r.users.Get(ctx, obj.UserID)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toUserModel(user), nil
}

// Product is the resolver for the product field. Resuelve el producto de la linea por su id.
func (r *orderItemResolver) Product(ctx context.Context, obj *model.OrderItem) (*model.Product, error) {
	product, err := r.products.Get(ctx, obj.ProductID)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toProductModel(product), nil
}

// Me is the resolver for the me field. Devuelve null si no hay usuario autenticado.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := authctx.UserID(ctx)
	if !ok {
		return nil, nil
	}
	user, err := r.users.Get(ctx, userID)
	if errors.Is(err, domain.ErrUserNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toUserModel(user), nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, filter *model.ProductFilter, page *int, pageSize *int) (*model.ProductPage, error) {
	result, err := r.products.List(ctx, toDomainFilter(filter), pageOr(page, 1), pageOr(pageSize, 20))
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toProductPage(result), nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	product, err := r.products.Get(ctx, id)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toProductModel(product), nil
}

// MyOrders is the resolver for the myOrders field.
func (r *queryResolver) MyOrders(ctx context.Context, page *int, pageSize *int) (*model.OrderPage, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	result, err := r.orders.MyOrders(ctx, userID, pageOr(page, 1), pageOr(pageSize, 20))
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toOrderPage(result), nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	userID, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	order, err := r.orders.Get(ctx, userID, id)
	if err != nil {
		return nil, toGraphQLError(ctx, err)
	}
	return toOrderModel(order), nil
}

// requireUser devuelve el id del usuario autenticado, o un error UNAUTHENTICATED ya mapeado.
func requireUser(ctx context.Context) (string, error) {
	userID, ok := authctx.UserID(ctx)
	if !ok {
		return "", toGraphQLError(ctx, domain.ErrUnauthenticated)
	}
	return userID, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Order returns generated.OrderResolver implementation.
func (r *Resolver) Order() generated.OrderResolver { return &orderResolver{r} }

// OrderItem returns generated.OrderItemResolver implementation.
func (r *Resolver) OrderItem() generated.OrderItemResolver { return &orderItemResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver  struct{ *Resolver }
	orderResolver     struct{ *Resolver }
	orderItemResolver struct{ *Resolver }
	queryResolver     struct{ *Resolver }
)
